### PR TITLE
[OSD-11454] add files to run linting with tox

### PR DESCRIPTION
**Pull request by dastergon**
This PR adds the [bandit](https://pypi.org/project/bandit/) linter to the project to run via tox.

* Added a pyproject file
* Added a make target for lint
* Added the basic tox file that runs bandit for security linting

Card: [OSD-11454](https://issues.redhat.com/browse/OSD-11454)

### CODE REVIEW

**Comment by jharrington22** [comment]
@dastergon whats the reason for using bandit here over some of the other standard linters for python?

**Comment by dastergon** [comment]
@jharrington22 that's what the team has decided

**Comment by jharrington22** [comment]
@bergmannf provided a good explanation of the bandit project [here](https://github.com/openshift/managed-prometheus-exporter-ebs-iops-reporter/pull/44#issuecomment-1183041317)

/approved
/lgtm

**Pull request merged**
