### PR TITLE
use openshift-sre/managed-prometheus-exporter-base …

### PR DESCRIPTION
**Pull request by fahlmant**
instead of jupierce/openshify-python-monitoring

https://issues.redhat.com/browse/OSD-6621

### CODE REVIEW

**Review by lisa — APPROVED** [review]
/lgtm
/approve
/hold

Unhold when freeze is over and you're ready.

**Comment by boranx** [comment]
@lisa guess it was rebased and its _lgtm_ was gone. Could we relabel? I'll be watching those if it gets merged

**Pull request merged**
